[package]
name = "namespacedkey_macro_test"
version = "1.0.0"
edition = "2024"
publish = false
rust-version = "1.88.0"

[dependencies]
namespacedkey = { path = "../..", version = "1.0.1", features = ["macro"] }

[lints]
workspace = true
